timeout: 1800s
substitutions:
  _TF_SA_PREFIX: 'terraform'

steps:
- id: 'setup'
  name: dizzyplan/gcp-devops-image
  entrypoint: '/bin/bash'
  args:
  - -c
  - |
    set -e
    if [[ ! -z "${_TF_SA_PREFIX}" ]]; then
      tf_sa_email=${_TF_SA_PREFIX}@${PROJECT_ID}.iam.gserviceaccount.com
      echo "Setting up gcloud for impersonation"
      gcloud config set auth/impersonate_service_account $tf_sa_email
    fi
    cd resources
    cp common_vars.json.example common_vars.json
    sed -i "s/_project_/${PROJECT_ID}/g" common_vars.json 
    cat common_vars.json

- id: 'validate'
  name: dizzyplan/gcp-devops-image
  entrypoint: '/bin/bash'
  args:
  - -c
  - |
    set -e
    echo "Setting up environment variables"
    source ./scripts/env.sh      
    if [[ ! -z "${_TF_SA_PREFIX}" ]]; then
      echo "Setting up oauth"
      source ./scripts/oauth.sh      
    fi
    make init
    make lint
    make validate

- id: 'action'
  name: dizzyplan/gcp-devops-image
  entrypoint: '/bin/bash'
  args:
    - -c
    - |
      set -e
      echo "Setting up environment variables"
      source ./scripts/env.sh
      if [[ ! -z "${_TF_SA_PREFIX}" ]]; then
        echo "Setting up oauth"
        source ./scripts/oauth.sh
      fi
      make init
      make ${_TF_ACTION}
      # Check cluster connectivity if creating cluster
      if [[ ${_TF_ACTION} == "apply" ]]; then
        make tunnel
      fi
